server:
  port: 8090
spring:
  application:
    name: turbine
security:
  user:
    name: wangjian
    password: 1234qwer
  basic:
    enabled: true

eureka:
  instance:
    hostname: 192.168.252.25
  client:
    # 是否注册到eureka
    register-with-eureka: true
    # 是否从eureka获取注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:8761/eureka/
logging:
  file: ${spring.application.name}.log
management:
  port: 8091
# turbine（说明：注意必须为大写，因为 eureka 返回的值都是大写的）
turbine:
  app-config: EUREKA-CONSUMER-RIBBON-HYSTRIX
  cluster-name-expression: new String("default")
  combine-host-port: true