server:
  port: 8093
spring:
  application:
    name: stream-hello
# 此处为链接rabbitMQ的url port name password
# 改用自己部署的rabbitMQ帐号以及密码
  rabbitmq:
    host: 192.168.254.236
    port: 5672
    username: wangjian
    password: 1234qwer
security:
  user:
    name: wangjian
    password: 1234qwer
  basic:
    enabled: true

eureka:
  instance:
    hostname: 192.168.252.25
  client:
    # 是否注册到eureka
    register-with-eureka: true
    # 是否从eureka获取注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:8761/eureka/
logging:
  file: ${spring.application.name}.log


